### ISSUE TITLE
Migrate starting services from daemon package to systemd config

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-etl-filemonitoring-remote#3]
The old Debian package "daemon" used for starting services in init.d start script causes problems on newer Debian and Ubuntu releases, since stopping/restarting the services doesn't work.

Migrate to modern systemd config.

Additionally
systemctl status opensemanticetl-filemonitoring
will show infos.

**Comment by Mandalka** [comment]
Migrated from init.d script to systemd config.
